name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: cachix
    permissions:
      id-token: "write"
      contents: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: judah-sotomayor
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run `nix build`
        run: nix build .#default .#tools-tarball
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            result/bin/jj-rs
            result/bin/jj-rs.exe
            result/bin/jj
            result/bin/jj.exe
            result/jj.tgz

